[package]
name = "slint-demo"
version = "0.1.0"
edition = "2024"

[features]
default = ["renderer-femtovg"]
renderer-femtovg = ["slint/renderer-femtovg"]
renderer-software = ["slint/renderer-software"]

[dependencies]
slint = { version = "~1.17", default-features = false, features = [
    "std",
    "compat-1-2",
    "backend-winit",
] }

[build-dependencies]
slint-build = "~1.17"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
incremental = false
