[package]
name = "slint-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "~1.17", default-features = false, features = [
    "std",
    "compat-1-2",
    "backend-winit",
    "renderer-femtovg",
] }

[build-dependencies]
slint-build = "~1.17"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
